### ISSUE TITLE
how to get videos longer than 2 sec?

### ISSUE THREAD

**Issue by cocktailpeanut** [PKU-YuanGroup/MagicTime#10]
Also what does the `video_length=16` imply? Is that number of frames? Tried changing it to 32 but it just seems to generate blank videos. Example:

https://github.com/PKU-YuanGroup/MagicTime/assets/121128867/c8268ee8-6c50-4bd7-a287-edb61761d78b

**Comment by SHYuanBest** [comment]
Thanks for your interest. The _video_length_ represents the number of frames. Our current open source MagicTime only supports generating 16-frame videos. We will release MagicTime-DiT based on [Open-Sora-Plan](https://github.com/PKU-YuanGroup/Open-Sora-Plan) in the future, which supports generating videos of up to 65 frames, so stay tuned. And there are some 10s (65x512x512) video samples generated by MagicTime-DiT in the README for preview.

**Comment by SHYuanBest** [comment]
There are some methods for training-free longer video generation, such as [FreeNoise](https://github.com/arthur-qiu/FreeNoise-LaVie) and [PromptTravel](https://github.com/Kahsolt/stable-diffusion-webui-prompt-travel), which may temporarily meet your needs.

**Comment by cocktailpeanut** [comment]
@SHYuanBest Ah I see, thank you for the answer! I do like how MagicTime is able to handle time-lapse compared to other methods, just wanted a longer video. After all, I believe the strength of this project (being able to generate videos with accurate transitions based on prompt) will be more highlighted if there's a way to generate longer videos. 2 seconds is not long enough to show its full power. 10 second would be awesome. Looking forward to the new model!

**Comment by SHYuanBest** [comment]
Thanks for your attention, we are speeding up the training of new version of the model! Although the video generated by MagicTime (open source) is only 2 seconds, the time span of the video content is very large. In theory, long videos can also be obtained by using a frame interpolation model for the generated results. This solution is different from existing long video generation methods, and our status changes will be greater. We have also mentioned it in the appendix in [Arxiv](https://arxiv.org/abs/2404.05014), welcome to check it out.
