### ISSUE TITLE
请问，视频时间是否可以设置，好像只有2秒的视频长度？

### ISSUE THREAD

**Issue by lckj2009** [PKU-YuanGroup/MagicTime#18]
视频长度只有2秒，好像还无法修改成更长的时间。

另外，基础模型是标准的SD1.5的整套框架，感觉质量有点差，是否考虑升级到SDXL或者更高的版本？

**Comment by SHYuanBest** [comment]
Thanks for your interest. For longer durations you can refer to this [issue](https://github.com/PKU-YuanGroup/MagicTime/issues/10). For the next question, We will consider your opinions and train based on sdxl in the future. By the way, we are currently training based on the more powerful Open-Sora-Plan, which will be released in the future.

**Comment by lckj2009** [comment]
> Thanks for your interest. For longer durations you can refer to this [issue](https://github.com/PKU-YuanGroup/MagicTime/issues/10). For the next question, We will consider your opinions and train based on sdxl in the future. By the way, we are currently training based on the more powerful [Open-Sora-Plan](https://github.com/PKU-YuanGroup/Open-Sora-Plan), which will be released in the future.

Thank you, I will continue to support your project
