### ISSUE TITLE
Encountered (N) file(s) that may not have been copied correctly on Windows

### ISSUE THREAD

**Issue by truedat101** [PKU-YuanGroup/MagicTime#19]
During base prepare

git clone https://huggingface.co/runwayml/stable-diffusion-v1-5 ckpts/Base_Model

Encountered (N) file(s) that may not have been copied correctly on Windows

Related issue discussed.

https://github.com/git-lfs/git-lfs/issues/4744

I think this can be treated as a warning.

**Comment by SHYuanBest** [comment]
Thanks for your interest. It seems that changing **git** to **git-lfs** can solve the problem on Windows.

**Comment by truedat101** [comment]
Actually this happened on Linux, however, the error is reported related to Windows.  I am not convinced it's more than a warning, and the error mentions something about git smudge .

**Comment by truedat101** [comment]
Will close.  Warning seems to be implied and the system will work properly.
