### ISSUE TITLE
Please provide argument or configuration to support multiple CUDA devices

### ISSUE THREAD

**Issue by truedat101** [PKU-YuanGroup/MagicTime#20]
Current set up defaults to GPU 0, and will run out of memory on a single GPU <= 8GB VRAM.  Ideally there is some configuration to support specifying the GPU to use, or a number of GPUs to use.

**Comment by SHYuanBest** [comment]
Thanks for your interest. We will take your suggestions into consideration and may update the multi-GPU version of the inference code in the future.

**Comment by truedat101** [comment]
Oh, is it just this?  CUDA_VISIBLE_DEVICES=0 

Change 0 to 0,1,...

**Comment by SHYuanBest** [comment]
Currently only the first GPU is used by default
