### ISSUE TITLE
Windows support for triton dependency is does not exist

### ISSUE THREAD

**Issue by truedat101** [PKU-YuanGroup/MagicTime#22]
During requirements install

```
ERROR: Could not find a version that satisfies the requirement triton (from versions: none)
ERROR: No matching distribution found for triton
```

https://github.com/openai/triton/issues/1057

**Comment by truedat101** [comment]
seems possible to install (this apparently is a CI server shortage at OpenAI somehow ...) pip install https://huggingface.co/r4ziel/xformers_pre_built/resolve/main/triton-2.0.0-cp310-cp310-win_amd64.whl

**Comment by SongOnWater** [comment]
"ERROR: Could not find a version that satisfies the requirement triton (from versions: none)
ERROR: No matching distribution found for triton" 
Same as on Mac M2

**Comment by truedat101** [comment]
I can't imagine this will run on m2 without some work.

**Comment by SHYuanBest** [comment]
Thanks for your interest. Is it solved now?

**Comment by truedat101** [comment]
I wasn't able to resolve on Windows, however, I didn't attempt to complete since the easier path was Linux.
