### ISSUE TITLE
大佬，带带弟弟！

### ISSUE THREAD

**Issue by CocoSgt** [PKU-YuanGroup/MagicTime#3]
我做了 WebPilot，以及「赛博禅心」，求交流，发了邮件了～

**Comment by inFaaa** [comment]
Thanks for your interest! We are still working hard to scale up the metamorphic time-lapse and develop a stronger model. We can discuss it after all is done. 

谢谢您感兴趣！我们正在努力扩大质变延迟摄影视频数据集以及研发更强的视频生成算法。我们可以之后交流！
