### ISSUE TITLE
Solving environment: failed, after run conda env create -f environment.yml

### ISSUE THREAD

**Issue by supwang** [PKU-YuanGroup/MagicTime#4]
Hi,

When I run the command: conda env create -f environment.yml
I got the error below, how to solve it? Thank you.

(base) D:\AI\MagicTime>conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - mkl_random==1.2.4=py310hdb19cb5_0
  - brotli-python==1.0.9=py310h6a678d5_7
  - lerc==3.0=h295c915_0
  - ncurses==6.4=h6a678d5_0
  - pip==23.3.1=py310h06a4308_0
  - mkl==2023.1.0=h213fc3f_46344
  - libtiff==4.5.1=h6a678d5_0
  - typing_extensions==4.9.0=py310h06a4308_1
  - freetype==2.12.1=h4a9f257_0
  - bzip2==1.0.8=h5eee18b_5
  - mkl-service==2.4.0=py310h5eee18b_1
  - zstd==1.5.5=hc292b87_0
  - libwebp-base==1.3.2=h5eee18b_0
  - lcms2==2.12=h3be6417_0
  - nettle==3.7.3=hbbd107a_1
  - python==3.10.13=h955ad1f_0
  - libpng==1.6.39=h5eee18b_0
  - lame==3.100=h7b6447c_0
  - setuptools==68.2.2=py310h06a4308_0
  - openjpeg==2.4.0=h3ad879b_0
  - pillow==10.2.0=py310h5eee18b_0
  - zlib==1.2.13=h5eee18b_0
  - gmp==6.2.1=h295c915_3
  - libcufft==10.7.2.124=h4fbf590_0
  - urllib3==2.1.0=py310h06a4308_1
  - idna==3.4=py310h06a4308_0
  - libidn2==2.3.4=h5eee18b_0
  - libunistring==0.9.10=h27cfd23_0
  - requests==2.31.0=py310h06a4308_1
  - libuuid==1.41.5=h5eee18b_0
  - wheel==0.41.2=py310h06a4308_0
  - _openmp_mutex==5.1=1_gnu
  - ca-certificates==2024.3.11=h06a4308_0
  - readline==8.2=h5eee18b_0
  - intel-openmp==2023.1.0=hdb19cb5_46306
  - gnutls==3.6.15=he1e5248_0
  - mkl_fft==1.3.8=py310h5eee18b_0
  - ld_impl_linux-64==2.38=h1181459_1
  - libdeflate==1.17=h5eee18b_1
  - numpy-base==1.26.4=py310hb5e798b_0
  - libffi==3.4.4=h6a678d5_0
  - libgomp==11.2.0=h1234567_1
  - openh264==2.1.1=h4ff587b_0
  - sqlite==3.41.2=h5eee18b_0
  - pytorch-cuda==11.7=h778d358_5
  - pytorch==1.13.1=py3.10_cuda11.7_cudnn8.5.0_0
  - pysocks==1.7.1=py310h06a4308_0
  - libcufile==1.9.0.20=0
  - libtasn1==4.19.0=h5eee18b_0
  - openssl==3.0.13=h7f8727e_0
  - ffmpeg==4.3=hf484d3e_0
  - tk==8.6.12=h1ccaba5_0
  - tbb==2021.8.0=hdb19cb5_0
  - numpy==1.26.4=py310h5f9d8c6_0
  - jpeg==9e=h5eee18b_1
  - libiconv==1.16=h7f8727e_2
  - libgcc-ng==11.2.0=h1234567_1
  - xz==5.4.6=h5eee18b_0
  - lz4-c==1.9.4=h6a678d5_0
  - libstdcxx-ng==11.2.0=h1234567_1
  - certifi==2024.2.2=py310h06a4308_0

**Comment by SHYuanBest** [comment]
Thanks for your interest! We also discovered this problem and are fixing it urgently.

**Comment by SHYuanBest** [comment]
The environment has been fixed, you can follow the latest instructions to configure it.
