### ISSUE TITLE
装不上，求助

### ISSUE THREAD

**Issue by gxbsyxh** [PKU-YuanGroup/MagicTime#7]
![386c1bd9bdbf74269ea7904ebfb504ce](https://github.com/PKU-YuanGroup/MagicTime/assets/148219027/3f13f2ad-f90d-4ada-8e97-6f7c31ff918f)

**Comment by SHYuanBest** [comment]
Thank you for your attention. You can try running "pip install ms-swift -U", or follow our installation instructions to reconfigure the environment

**Comment by gxbsyxh** [comment]
> 感谢您的关注。您可以尝试运行“pip install ms-swift -U”，或按照我们的安装说明重新配置环境
感谢您忙碌中来回复，但是它依然没有工作，comfyui便携版本，不管是在系统cmd，还是在\ComfyUI_windows_portable\python_embeded 下都一样，在python_embeded下操作会出现其它错误如下：
 Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-mil7oy0z\aliyun-python-sdk-core_b3a24b54b6714bf6acce9ddc389e52d1\setup.py", line 41, in <module>
          VERSION = __import__(PACKAGE).__version__
      ModuleNotFoundError: No module named 'aliyunsdkcore'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by SHYuanBest** [comment]
It seems that "aliyunsdkcore" is not installed. This part may be related to the configuration of comfyui rather than the MagicTime environment. We haven't tried deploying it on comfyui yet, but in theory it should be feasible. Maybe you can refer to this [issue](https://github.com/PKU-YuanGroup/Open-Sora-Plan/issues/222).

**Comment by SHYuanBest** [comment]
Someone has successfully run MagicTime on ComfyUI, you can refer to it.
[ComfyUI-MagicTimeWrapper](https://github.com/kijai/ComfyUI-MagicTimeWrapper) (by [@Jukka Seppänen](https://github.com/kijai))

**Comment by shanyu333** [comment]
I had the same problem and solved it.

**Comment by shanyu333** [comment]
我在comfyui中安装成功了，使用的是comfyui-MagicTimeWrapper这个插件。
我用的是官方整合包，在整合包右键-在终端打开并安装：.\python_embeded\python.exe -m pip install aliyun-python-sdk-core-v3==2.13.10
然后安装依赖就会成功：python_embeded\python.exe -m pip install -r ComfyUI\custom_nodes\ComfyUI-MagicTimeWrapper\requirements.txt

**Comment by SHYuanBest** [comment]
Thanks for your feedback.
