### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [PKU-YuanGroup/MagicTime#8]
Hi,
Thanks for releasing this amazing project!
MagicTime is licensed under Apache 2.0, but it says "The service is a research preview intended for non-commercial use only. Please contact us if you find any potential violations."
Apache 2.0 is an open source license, which inherently allows commercial use. But this statement seems to conflict the license.
Would you mind clarifying?
Thank you!

**Comment by inFaaa** [comment]
Thanks for your kind reminder. We will change the license from Apache 2.0 to MIT license. 💗

**Comment by fakerybakery** [comment]
Hi, thanks for your response! The MIT license also inherently allows commercial use. Is your intention to make this repo non-commercial only? (Which would make it not open source)

**Comment by inFaaa** [comment]
Hi, we continue to use the Apache 2.0 license and have edited "The service is a research preview. Please contact us if you find any potential violations." for clarification. Thanks again!

**Comment by fakerybakery** [comment]
Cool, thanks!
